-- ====================================================================
-- Ticket Automation Database Schema & Seed Data
-- ====================================================================

-- 1. Create Core Tables
CREATE TABLE IF NOT EXISTS public.auth_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.panel_business_unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    enterprise_id BIGINT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.panel_site (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    bu_id BIGINT REFERENCES public.panel_business_unit(id),
    enterprise_id BIGINT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.panel_user_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.auth_user(id),
    role VARCHAR(50) DEFAULT 'agent',
    on_break BOOLEAN DEFAULT FALSE,
    on_shift_end BOOLEAN DEFAULT FALSE,
    last_active TIMESTAMP WITH TIME ZONE,
    "tickets_inHand" BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.panel_user_profile_bu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT REFERENCES public.panel_user_profile(id),
    business_unit_id BIGINT REFERENCES public.panel_business_unit(id)
);

CREATE TABLE IF NOT EXISTS public.panel_ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT REFERENCES public.panel_site(id),
    assigned_to_id BIGINT REFERENCES public.auth_user(id),
    assigned_at TIMESTAMP WITH TIME ZONE,
    is_parent BOOLEAN DEFAULT TRUE,
    closed BOOLEAN DEFAULT FALSE,
    closed_at TIMESTAMP WITH TIME ZONE,
    "isAccepted" BOOLEAN DEFAULT FALSE,
    accepted_at TIMESTAMP WITH TIME ZONE,
    comments TEXT
);

CREATE TABLE IF NOT EXISTS public.panel_ticket_children_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_ticket_id BIGINT REFERENCES public.panel_ticket(id),
    to_ticket_id BIGINT REFERENCES public.panel_ticket(id)
);

CREATE TABLE IF NOT EXISTS public.panel_ticketassignmenttransaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_ticket_id BIGINT REFERENCES public.panel_ticket(id),
    user_id BIGINT REFERENCES public.auth_user(id)
);

CREATE TABLE IF NOT EXISTS public.panel_ticketassignmenttransaction_safebox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_ticket_id BIGINT REFERENCES public.panel_ticket(id),
    user_id BIGINT REFERENCES public.auth_user(id)
);

CREATE TABLE IF NOT EXISTS public.panel_ticketassignmenttransaction_safeboxai (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_ticket_id BIGINT REFERENCES public.panel_ticket(id),
    user_id BIGINT REFERENCES public.auth_user(id)
);

-- 2. Create Stored Procedures / Functions
CREATE OR REPLACE FUNCTION expire_panel_tickets_summary()
RETURNS TABLE(summary_message TEXT, closed_tickets_count BIGINT) AS $$
DECLARE
    v_closed_count BIGINT;
BEGIN
    UPDATE public.panel_ticket
    SET closed = TRUE,
        closed_at = NOW(),
        comments = COALESCE(comments, '') || ' [Expired by automation]'
    WHERE closed = FALSE
      AND assigned_at < NOW() - INTERVAL '24 hours'
      AND is_parent = TRUE;
    
    GET DIAGNOSTICS v_closed_count = ROW_COUNT;
    
    RETURN QUERY SELECT 'Panel tickets expired successfully'::TEXT, v_closed_count;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION expire_safebox_tickets_summary()
RETURNS TABLE(summary_message TEXT, closed_tickets_count BIGINT) AS $$
BEGIN
    RETURN QUERY SELECT 'Safebox tickets expired successfully'::TEXT, 0::BIGINT;
END;
$$ LANGUAGE plpgsql;

-- ====================================================================
-- 3. Seed Data (Reset & Populate)
-- ====================================================================

-- Clean existing data before seeding to allow idempotent resets
TRUNCATE TABLE 
    public.panel_ticket_children_tickets,
    public.panel_ticketassignmenttransaction,
    public.panel_ticketassignmenttransaction_safebox,
    public.panel_ticketassignmenttransaction_safeboxai,
    public.panel_ticket,
    public.panel_user_profile_bu,
    public.panel_user_profile,
    public.panel_site,
    public.panel_business_unit,
    public.auth_user
RESTART IDENTITY CASCADE;

-- 3.1 Business Units
INSERT INTO public.panel_business_unit (id, name, enterprise_id) VALUES
    (1, 'North Zone Support BU', 1),
    (2, 'South Zone Support BU', 1),
    (34, 'Enterprise 34 Excluded BU', 34)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, enterprise_id = EXCLUDED.enterprise_id;

-- 3.2 Sites
INSERT INTO public.panel_site (id, name, bu_id, enterprise_id) VALUES
    (10, 'Delhi NCR Tech Park', 1, 1),
    (20, 'Bangalore Hub Site', 2, 1),
    (340, 'Special Enterprise Site (ID 34)', 34, 34)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, bu_id = EXCLUDED.bu_id, enterprise_id = EXCLUDED.enterprise_id;

-- 3.3 Auth Users
-- 602 is the designated NoAgentID
INSERT INTO public.auth_user (id, username) VALUES
    (602, 'no_agent'),
    (101, 'agent_alice'),
    (102, 'agent_bob'),
    (103, 'agent_charlie'),
    (104, 'agent_david'),
    (105, 'agent_on_break'),
    (106, 'agent_shift_ended')
ON CONFLICT (id) DO UPDATE SET username = EXCLUDED.username;

-- 3.4 User Profiles
-- Note: 'tickets_inHand' requires double quotes in PostgreSQL due to camelCase
INSERT INTO public.panel_user_profile (id, user_id, role, on_break, on_shift_end, last_active, "tickets_inHand") VALUES
    -- System / Fallback profile
    (602, 602, 'system', FALSE, FALSE, NOW(), 0),
    -- BU 1 Active Agents (Active right now)
    (1, 101, 'agent', FALSE, FALSE, NOW(), 0),
    (2, 102, 'agent', FALSE, FALSE, NOW(), 0),
    -- BU 2 Inactive Agent (last_active > 15 minutes ago, will be marked on_shift_end = true)
    (3, 103, 'agent', FALSE, FALSE, NOW() - INTERVAL '30 minutes', 1),
    -- BU 2 Active Agent (Available to take over charlie's tickets)
    (4, 104, 'agent', FALSE, FALSE, NOW(), 0),
    -- Agents that should NOT receive tickets
    (5, 105, 'agent', TRUE, FALSE, NOW(), 0),
    (6, 106, 'agent', FALSE, TRUE, NOW(), 0)
ON CONFLICT (id) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    role = EXCLUDED.role,
    on_break = EXCLUDED.on_break,
    on_shift_end = EXCLUDED.on_shift_end,
    last_active = EXCLUDED.last_active,
    "tickets_inHand" = EXCLUDED."tickets_inHand";

-- 3.5 User Profile - Business Unit Mappings
INSERT INTO public.panel_user_profile_bu (id, user_profile_id, business_unit_id) VALUES
    (1, 1, 1),
    (2, 2, 1),
    (3, 3, 2),
    (4, 4, 2),
    (5, 5, 1),
    (6, 6, 1),
    (7, 602, 1),
    (8, 602, 2)
ON CONFLICT (id) DO UPDATE SET user_profile_id = EXCLUDED.user_profile_id, business_unit_id = EXCLUDED.business_unit_id;

-- 3.6 Tickets
-- Scenario A: DistributeNoAgent (Assigned to 602 -> should reassign to alice 101 / bob 102)
-- Scenario B: InactiveUsers (Assigned to charlie 103 -> should reassign to david 104)
-- Scenario C: GetClosedTransactions (Parent closed -> child closed & txn deleted)
-- Scenario D: Enterprise 34 ticket (Assigned to 602 -> should stay with 602 because enterprise_id == 34)
INSERT INTO public.panel_ticket (
    id, site_id, assigned_to_id, assigned_at, is_parent, closed, closed_at, "isAccepted", accepted_at, comments
) VALUES
    -- SCENARIO A: Tickets assigned to no_agent (602) in BU 1
    (1001, 10, 602, NOW() - INTERVAL '10 minutes', TRUE, FALSE, NULL, FALSE, NULL, 'Unassigned Parent Ticket 1'),
    (1002, 10, 602, NOW() - INTERVAL '10 minutes', FALSE, FALSE, NULL, FALSE, NULL, 'Unassigned Child Ticket 1'),
    (1003, 10, 602, NOW() - INTERVAL '8 minutes', TRUE, FALSE, NULL, FALSE, NULL, 'Unassigned Parent Ticket 2'),
    (1004, 10, 602, NOW() - INTERVAL '8 minutes', FALSE, FALSE, NULL, FALSE, NULL, 'Unassigned Child Ticket 2'),

    -- Excluded Enterprise 34 ticket (should NOT be redistributed)
    (1099, 340, 602, NOW() - INTERVAL '10 minutes', TRUE, FALSE, NULL, FALSE, NULL, 'Enterprise 34 Parent Ticket'),

    -- SCENARIO B: Ticket assigned to inactive agent charlie (103) in BU 2
    (2001, 20, 103, NOW() - INTERVAL '40 minutes', TRUE, FALSE, NULL, FALSE, NULL, 'Inactive Agent Parent Ticket'),
    (2002, 20, 103, NOW() - INTERVAL '40 minutes', FALSE, FALSE, NULL, FALSE, NULL, 'Inactive Agent Child Ticket'),

    -- SCENARIO C: Closed parent tickets with open children and active transactions
    -- Normal transaction
    (3001, 10, 101, NOW() - INTERVAL '2 hours', TRUE, TRUE, NOW() - INTERVAL '1 hour', TRUE, NOW() - INTERVAL '1 hour', 'Parent Resolved by Alice'),
    (3002, 10, 101, NOW() - INTERVAL '2 hours', FALSE, FALSE, NULL, FALSE, NULL, 'Child Ticket pending sync'),

    -- Safebox transaction
    (3003, 10, 101, NOW() - INTERVAL '2 hours', TRUE, TRUE, NOW() - INTERVAL '45 minutes', TRUE, NOW() - INTERVAL '45 minutes', 'Safebox Parent Resolved'),
    (3004, 10, 101, NOW() - INTERVAL '2 hours', FALSE, FALSE, NULL, FALSE, NULL, 'Safebox Child Ticket pending sync'),

    -- Safebox AI transaction
    (3005, 10, 101, NOW() - INTERVAL '2 hours', TRUE, TRUE, NOW() - INTERVAL '30 minutes', TRUE, NOW() - INTERVAL '30 minutes', 'Safebox AI Parent Resolved'),
    (3006, 10, 101, NOW() - INTERVAL '2 hours', FALSE, FALSE, NULL, FALSE, NULL, 'Safebox AI Child Ticket pending sync')
ON CONFLICT (id) DO UPDATE SET
    site_id = EXCLUDED.site_id,
    assigned_to_id = EXCLUDED.assigned_to_id,
    assigned_at = EXCLUDED.assigned_at,
    is_parent = EXCLUDED.is_parent,
    closed = EXCLUDED.closed,
    closed_at = EXCLUDED.closed_at,
    "isAccepted" = EXCLUDED."isAccepted",
    accepted_at = EXCLUDED.accepted_at,
    comments = EXCLUDED.comments;

-- 3.7 Parent-Child Relationships
INSERT INTO public.panel_ticket_children_tickets (id, from_ticket_id, to_ticket_id) VALUES
    (1, 1001, 1002),
    (2, 1003, 1004),
    (3, 2001, 2002),
    (4, 3001, 3002),
    (5, 3003, 3004),
    (6, 3005, 3006)
ON CONFLICT (id) DO UPDATE SET from_ticket_id = EXCLUDED.from_ticket_id, to_ticket_id = EXCLUDED.to_ticket_id;

-- 3.8 Transactions
-- Active transactions for no_agent parent tickets
INSERT INTO public.panel_ticketassignmenttransaction (id, parent_ticket_id, user_id) VALUES
    (101, 1001, 602),
    (102, 1003, 602),
    (201, 2001, 103),
    -- Transaction for closed ticket (should be cleaned up / deleted)
    (301, 3001, 101)
ON CONFLICT (id) DO UPDATE SET parent_ticket_id = EXCLUDED.parent_ticket_id, user_id = EXCLUDED.user_id;

-- Safebox transaction for closed ticket (should be deleted)
INSERT INTO public.panel_ticketassignmenttransaction_safebox (id, parent_ticket_id, user_id) VALUES
    (302, 3003, 101)
ON CONFLICT (id) DO UPDATE SET parent_ticket_id = EXCLUDED.parent_ticket_id, user_id = EXCLUDED.user_id;

-- Safebox AI transaction for closed ticket (should be deleted)
INSERT INTO public.panel_ticketassignmenttransaction_safeboxai (id, parent_ticket_id, user_id) VALUES
    (303, 3005, 101)
ON CONFLICT (id) DO UPDATE SET parent_ticket_id = EXCLUDED.parent_ticket_id, user_id = EXCLUDED.user_id;

-- 3.9 Update Sequence Generators so subsequent inserts work properly
SELECT setval('auth_user_id_seq', COALESCE((SELECT MAX(id) FROM auth_user), 1));
SELECT setval('panel_business_unit_id_seq', COALESCE((SELECT MAX(id) FROM panel_business_unit), 1));
SELECT setval('panel_site_id_seq', COALESCE((SELECT MAX(id) FROM panel_site), 1));
SELECT setval('panel_user_profile_id_seq', COALESCE((SELECT MAX(id) FROM panel_user_profile), 1));
SELECT setval('panel_user_profile_bu_id_seq', COALESCE((SELECT MAX(id) FROM panel_user_profile_bu), 1));
SELECT setval('panel_ticket_id_seq', COALESCE((SELECT MAX(id) FROM panel_ticket), 1));
SELECT setval('panel_ticket_children_tickets_id_seq', COALESCE((SELECT MAX(id) FROM panel_ticket_children_tickets), 1));
SELECT setval('panel_ticketassignmenttransaction_id_seq', COALESCE((SELECT MAX(id) FROM panel_ticketassignmenttransaction), 1));
SELECT setval('panel_ticketassignmenttransaction_safebox_id_seq', COALESCE((SELECT MAX(id) FROM panel_ticketassignmenttransaction_safebox), 1));
SELECT setval('panel_ticketassignmenttransaction_safeboxai_id_seq', COALESCE((SELECT MAX(id) FROM panel_ticketassignmenttransaction_safeboxai), 1));
